"""Add the authentication tables: user, auth_session, api_token.

Autogenerated against a database already at 0002, then made idempotent by
hand, and verified with `alembic check` (no drift) plus a downgrade/upgrade
roundtrip.

Written by the orchestrator rather than the auth author: that agent
deliberately defined the ORM models and wrote no migration, because a
concurrent agent owned `alembic/` at the time. This is that reconciliation.

Revision ID: 0003_auth_tables
Revises: 0002_media_asset_reclaimed_at_index
Create Date: 2026-08-08 19:03:08.417618+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_auth_tables"
down_revision: str | None = "0002_media_asset_reclaimed_at_index"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _existing_tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    """Create the three auth tables, skipping any that already exist.

    The skip is deliberate, and follows revision 0002's precedent.

    `create_all()` still runs on every app and CLI startup -- ADR-035 kept it,
    and kept `db/session.py`'s ALTER TABLE patcher, because nothing calls
    `alembic upgrade head` at startup yet. So an operator who deploys and
    restarts *before* stamping and migrating already has these three tables,
    and a bare CREATE TABLE would abort the upgrade with "table user already
    exists", leaving the database stranded mid-migration.

    The documented adoption order (stamp, upgrade, then deploy) avoids that.
    But an upgrade path that only works if the operator reads the docs in the
    right order is not much of an upgrade path, and this failure would land on
    a live station holding 48,000 detections.

    Indexes are created inside the same guard rather than separately: SQLite
    creates them with the table here, and an existing table implies its
    indexes came from the same `create_all()` that made it.
    """
    existing = _existing_tables()

    if "user" not in existing:
        op.create_table(
            "user",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("username", sa.String(length=80), nullable=False),
            sa.Column("password_hash", sa.String(length=200), nullable=False),
            sa.Column("must_change_password", sa.Boolean(), nullable=False),
            sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("user", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    if "api_token" not in existing:
        op.create_table(
            "api_token",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("user_id", sa.Uuid(), nullable=False),
            sa.Column("name", sa.String(length=120), nullable=False),
            sa.Column("token_prefix", sa.String(length=16), nullable=False),
            sa.Column("token_hash", sa.String(length=64), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("token_hash"),
        )
        with op.batch_alter_table("api_token", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_api_token_token_prefix"), ["token_prefix"], unique=False
            )
            batch_op.create_index(batch_op.f("ix_api_token_user_id"), ["user_id"], unique=False)

    if "auth_session" not in existing:
        op.create_table(
            "auth_session",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("user_id", sa.Uuid(), nullable=False),
            sa.Column("token_hash", sa.String(length=64), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("user_agent", sa.String(length=300), nullable=False),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("auth_session", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_auth_session_expires_at"), ["expires_at"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_auth_session_token_hash"), ["token_hash"], unique=True
            )
            batch_op.create_index(batch_op.f("ix_auth_session_user_id"), ["user_id"], unique=False)


def downgrade() -> None:
    """Drop the auth tables. Only what exists, for symmetry with upgrade().

    This destroys accounts, sessions and API tokens. That is the honest
    meaning of downgrading past the revision that introduced them, but it is
    worth saying out loud: there is no backup taken here.
    """
    existing = _existing_tables()

    if "auth_session" in existing:
        with op.batch_alter_table("auth_session", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_auth_session_user_id"))
            batch_op.drop_index(batch_op.f("ix_auth_session_token_hash"))
            batch_op.drop_index(batch_op.f("ix_auth_session_expires_at"))
        op.drop_table("auth_session")

    if "api_token" in existing:
        with op.batch_alter_table("api_token", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_api_token_user_id"))
            batch_op.drop_index(batch_op.f("ix_api_token_token_prefix"))
        op.drop_table("api_token")

    if "user" in existing:
        with op.batch_alter_table("user", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_user_username"))
        op.drop_table("user")
