"""initial schema

Baseline revision matching the schema `create_all()` has been building since
before this migration environment existed (ADR-035; HANDOVER.md 6.3 item 10).
Every table and column present in ``src/open_observatory/db/models.py`` as of
2026-08-08 is included, including ``media_asset.reclaimed_at``,
``media_asset.reclaim_reason`` (ADR-026) and ``audio_stream.last_frame_at_utc``
(ADR-024) -- the three columns that were previously only reachable through
the defensive ``ALTER TABLE`` patcher in ``db/session.py``.

Autogenerated from an empty database against ``Base.metadata``, then
verified: running ``alembic revision --autogenerate`` again against a
database built by this revision produces an *empty* diff. That comparison,
not code review, is what makes this baseline honest -- see
``docs/data/DATA_MODEL.md`` for how to re-run it.

An existing SQLite database (the live station, or a developer's) that was
built by ``create_all()`` has this exact schema already and must never run
``upgrade()`` from scratch -- it would try to ``CREATE TABLE`` over live
data. Stamp it instead: ``alembic stamp 0001_initial``. See
``docs/data/DATA_MODEL.md`` "Adopting migrations on an existing database".

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-08 18:29:20.029219+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detector',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sa.String(length=80), nullable=False),
    sa.Column('plugin_version', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=True),
    sa.Column('taxonomy_version', sa.String(length=120), nullable=True),
    sa.Column('licence_name', sa.String(length=160), nullable=False),
    sa.Column('licence_url', sa.String(length=400), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('calibrated', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detector', schema=None) as batch_op:
        batch_op.create_index(
            'ix_detector_identity',
            ['plugin_id', 'plugin_version', 'model_version'],
            unique=True,
        )
        batch_op.create_index(batch_op.f('ix_detector_plugin_id'), ['plugin_id'], unique=False)

    op.create_table('health_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_event_service'), ['service'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_event_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_event_start_utc'), ['start_utc'], unique=False)

    op.create_table('media_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_uri', sa.String(length=600), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=True),
    sa.Column('source_start_frame', sa.BigInteger(), nullable=True),
    sa.Column('source_end_frame', sa.BigInteger(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('byte_length', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('reclaimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reclaim_reason', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_asset_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_reclaimed_at'), ['reclaimed_at'], unique=False)

    op.create_table('station',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('software_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('stable_device_key', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('usb_vendor_id', sa.String(length=16), nullable=True),
    sa.Column('usb_product_id', sa.String(length=16), nullable=True),
    sa.Column('usb_serial', sa.String(length=64), nullable=True),
    sa.Column('alsa_address', sa.String(length=120), nullable=True),
    sa.Column('negotiated_sample_rate', sa.Integer(), nullable=True),
    sa.Column('negotiated_format', sa.String(length=32), nullable=True),
    sa.Column('negotiated_channels', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_device', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_audio_device_stable_device_key'), ['stable_device_key'], unique=True
        )

    op.create_table('detection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('detector_id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('window_id', sa.Uuid(), nullable=False),
    sa.Column('event_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_start_frame', sa.BigInteger(), nullable=False),
    sa.Column('source_end_frame', sa.BigInteger(), nullable=False),
    sa.Column('detector_label', sa.String(length=240), nullable=True),
    sa.Column('common_name', sa.String(length=240), nullable=True),
    sa.Column('scientific_name', sa.String(length=240), nullable=True),
    sa.Column('canonical_taxon_id', sa.String(length=120), nullable=True),
    sa.Column('rank', sa.String(length=32), nullable=True),
    sa.Column('taxonomic_group', sa.String(length=48), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('peak_frequency_hz', sa.Float(), nullable=True),
    sa.Column('native_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_detection_canonical_taxon_id'), ['canonical_taxon_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_detection_detector_id'), ['detector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_event_start_utc'), ['event_start_utc'], unique=False)
        batch_op.create_index(
            'ix_detection_group_start', ['taxonomic_group', 'event_start_utc'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_detection_station_id'), ['station_id'], unique=False)
        batch_op.create_index(
            'ix_detection_station_start', ['station_id', 'event_start_utc'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_detection_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_taxonomic_group'), ['taxonomic_group'], unique=False)

    op.create_table('audio_stream',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audio_device_id', sa.Uuid(), nullable=True),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_monotonic_ns', sa.BigInteger(), nullable=False),
    sa.Column('end_monotonic_ns', sa.BigInteger(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('sample_format', sa.String(length=32), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('frame_count', sa.BigInteger(), nullable=False),
    sa.Column('discontinuity_count', sa.Integer(), nullable=False),
    sa.Column('end_reason', sa.String(length=64), nullable=True),
    sa.Column('last_frame_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['audio_device_id'], ['audio_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_stream', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_stream_start_utc'), ['start_utc'], unique=False)

    op.create_table('detection_media',
    sa.Column('detection_id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], ),
    sa.PrimaryKeyConstraint('detection_id', 'media_asset_id')
    )
    op.create_table('review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('corrected_taxon_id', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('supersedes_review_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['supersedes_review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_detection_id'), ['detection_id'], unique=False)

    op.create_table('capture_gap',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('start_monotonic_ns', sa.BigInteger(), nullable=False),
    sa.Column('end_monotonic_ns', sa.BigInteger(), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_missing_frames', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['audio_stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_gap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_gap_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index('ix_gap_stream_start', ['stream_id', 'start_monotonic_ns'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Hand-simplified from the autogenerated form: dropping a table drops its
    # indexes with it on both SQLite and PostgreSQL, so the explicit
    # batch_alter_table/drop_index calls autogenerate emitted here were both
    # redundant and fragile -- they broke if a later migration (0002) had
    # already dropped the same index by name. Table order is the reverse of
    # `upgrade()`, satisfying every foreign key below.
    op.drop_table('capture_gap')
    op.drop_table('review')
    op.drop_table('detection_media')
    op.drop_table('audio_stream')
    op.drop_table('detection')
    op.drop_table('audio_device')
    op.drop_table('station')
    op.drop_table('media_asset')
    op.drop_table('health_event')
    op.drop_table('detector')
